@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION
SET PATH=D:\ABHISHEK_DUTTA\WORK\DAILY_LOGS\
SET Y=2020
SET M=09
FOR /L %%I IN (1,1,31) DO ( 
  IF %%I GTR 9 (SET "D=%%I") ELSE (SET "D=0%%I")  
  SET FNAME=%PATH%%Y%%M%!D!.txt
  (ECHO NOTE FOR !D!-%M%-%Y%.
  ECHO DISCUSSIONS: 
  ECHO 1.  
  ECHO 2.  
  ECHO REMARKS:
  ECHO 1.) > !FNAME!
)